### ISSUE TITLE
Error download PSOL

### ISSUE THREAD

**Issue by KashifHK123** [Prihod/vestacp_nginx_pagespeed_http2#2]
> Centos 7 

ngnx [1.14.2]
openssl [1.1.0g]
pagespeed [1.12.34.3-stable]

```
Start download PSOL
--2018-12-20 19:33:16--  https://dl.google.com/dl/page-speed/psol/1.12.34.3-stable.tar.gz
Resolving dl.google.com (dl.google.com)... 216.58.210.14, 2a00:1450:4001:820::200e
Connecting to dl.google.com (dl.google.com)|216.58.210.14|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-12-20 19:33:17 ERROR 404: Not Found.

Error download PSOL
```

**Comment by Prihod** [comment]
Enter version pagespeed  1.12.34.2-x64

This script is for **Debian and Ubuntu**. Most likely it will not work correctly in Centos OS

**Comment by KashifHK123** [comment]
**Can you do some changing in script and create another repo for centos?**

**Comment by Prihod** [comment]
Updated the script. Now it can be used for CentOS

**Comment by KashifHK123** [comment]
**Thank you for update for Centos but i'm facing this issue**
```
checking for OS
 + Linux 3.10.0-862.14.4.el7.x86_64 x86_64
checking for C compiler ... not found

./configure: error: C compiler cc is not found

Error configure Nginx

```

**Comment by KashifHK123** [comment]
Thank you for Centos Update. I have setup it successfully but it not working, it is result of my server site and it using HTTP2 Proxy Template.
```
HTTP/1.1 200 OK
Server: nginx
Date: Sun, 23 Dec 2018 02:50:31 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Keep-Alive: timeout=60
X-Powered-By: PHP/7.3.0RC6
Set-Cookie: PHPSESSID=r9antkfktov0606el4miiqoith; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache

```

**Comment by Prihod** [comment]
You need  enable SSL support in Vesta  for your domain http://prntscr.com/lyl7co

**Comment by Prihod** [comment]
Without SSL enabled, everything also works.   Сheck your site here https://ismodpagespeedworking.com/

**Comment by KashifHK123** [comment]
SSL is already active at domain before install pagespeed module and i'm using http2 proxy template...

**Comment by KashifHK123** [comment]
Thank you....
