### ISSUE TITLE
./rebuild.sh: 88: ./rebuild.sh: Bad substitution

### ISSUE THREAD

**Issue by smkerz** [Prihod/vestacp_nginx_pagespeed_http2#3]
Hello! I tried your script with the following parameters:

Nginx [1.16.0]
OpenSSL [1.1.1a]
PageSpeed [1.13.35.2-stable]

and I had this issue:

./rebuild.sh: 88: ./rebuild.sh: Bad substitution

Kind regards,

**Comment by pafnuty** [comment]
@smkerz This aswer helps me https://stackoverflow.com/questions/20615217/bash-bad-substitution/20616103#20616103
